In [56]:
import pandas as pd
import numpy as np
import plotly.graph_objs as go
import plotly.io as pio
import plotly.express as px
pio.renderers.default='plotly_mimetype+notebook'
from ipywidgets import widgets as wg
import yfinance as yf
import requests

In [57]:

r = requests.get('https://finance.yahoo.com/world-indices/')
c = r.content
df_list = pd.read_html(c)

majorStockIdx = df_list[0]
majorStockIdx.head()

,Symbol,Name,Last Price,Change,% Change,Volume,Intraday High/Low,52 Week Range,Day Chart
0,^GSPC,S&P 500,4578.66,57.12,+1.26%,1.323B,NaN,NaN,NaN
1,^DJI,Dow 30,35745.59,282.81,+0.80%,175.422M,NaN,NaN,NaN
2,^IXIC,Nasdaq,14422.42,227.96,+1.61%,2.63B,NaN,NaN,NaN
3,^NYA,NYSE COMPOSITE (DJ),17051.62,197.92,+1.17%,0,NaN,NaN,NaN
4,^XAX,NYSE AMEX COMPOSITE INDEX,3725.28,13.34,+0.36%,0,NaN,NaN,NaN

In [58]:
# ^GSPC is the symbol of S&P 500 in Yahoo! Finance
tickerData = yf.Ticker('^GSPC')

In [59]:
#We Set the period we want to analyze
tickerDf1 = tickerData.history(period='1d', start='2019-1-1', end='2022-1-1')

In [60]:
# Now it’s time to collect historical data of ALL stock indices.
stock_list = []
for s in majorStockIdx.Symbol: # iterate for every stock indices
    # Retrieve data from Yahoo! Finance
    tickerData = yf.Ticker(s)
    tickerDf1 = tickerData.history(period='1d', start='2019-1-1', end='2022-1-1')
    # Save historical data 
    tickerDf1['ticker'] = s # don't forget to specify the index
    stock_list.append(tickerDf1)
# Concatenate all data
msi = pd.concat(stock_list, axis = 0)
msi

- ^CASE30: No data found for this date range, symbol may be delisted

,Open,High,Low,Close,Volume,Dividends,Stock Splits,ticker,Adj Close
Date,,,,,,,,,
2018-12-31,2498.939941,2509.239990,2482.820068,2506.850098,3.442870e+09,0.0,0.0,^GSPC,NaN
2019-01-02,2476.959961,2519.489990,2467.469971,2510.030029,3.733160e+09,0.0,0.0,^GSPC,NaN
2019-01-03,2491.919922,2493.139893,2443.959961,2447.889893,3.822860e+09,0.0,0.0,^GSPC,NaN
2019-01-04,2474.330078,2538.070068,2474.330078,2531.939941,4.213410e+09,0.0,0.0,^GSPC,NaN
2019-01-07,2535.610107,2566.159912,2524.560059,2549.689941,4.104710e+09,0.0,0.0,^GSPC,NaN
...,...,...,...,...,...,...,...,...,...
2021-12-24,4485.729980,4511.569824,4469.770020,4469.770020,0.000000e+00,0.0,0.0,^JN0U.JO,NaN
2021-12-28,4499.930176,4518.229980,4475.069824,4483.129883,0.000000e+00,0.0,0.0,^JN0U.JO,NaN
2021-12-29,4487.479980,4511.720215,4466.270020,4497.149902,0.000000e+00,0.0,0.0,^JN0U.JO,NaN
2021-12-30,4483.770020,4534.509766,4478.740234,4513.180176,0.000000e+00,0.0,0.0,^JN0U.JO,NaN
2021-12-31,4540.000000,4547.129883,4508.879883,4516.109863,0.000000e+00,0.0,0.0,^JN0U.JO,NaN

In [61]:
#The first step that I would like to do is to categorize each index by the region. 
#Here is my definition of the region:

region_idx= { 'US & Canada' : ['^GSPC', '^DJI', '^IXIC', '^RUT','^GSPTSE'],
  'Europe' : ['^FTSE', '^GDAXI', '^FCHI', '^STOXX50E','^N100', '^BFX']
}